### ISSUE TITLE
Class 'PHPUnit_Framework_TestCase' not found

### ISSUE THREAD

**Issue by mhnatiuk** [snscripts/itc-reporter#3]
Hi,
I'm trying to run basic test of this tool and it fails with:

`mikolaj@hal9002:~/projects/itc-reporter/tests$ php ReporterTest.php 
PHP Fatal error:  Class 'PHPUnit_Framework_TestCase' not found in /home/mikolaj/projects/itc-reporter/tests/ReporterTest.php on line 8
`

**Comment by mikebarlow** [comment]
Hi,
This is my fault for not adding a section on how to run the tests in the readme.

First, if you have not done so, you will need to do a `composer install` from the root itc-reporter folder. 
Then you will need to run the tests through PHPUnit by running `./vendor/bin/phpunit`, again from the root itc-reporter folder.
