### ISSUE TITLE
Not receving data

### ISSUE THREAD

**Issue by muresanandrei** [snscripts/itc-reporter#4]
This works $Reporter->getSalesAccounts();
 But the rest of the methods return empty array I am sure I am using the correct account number. What can be wrong?

**Comment by fedoco** [comment]
Did you try Apple's official Reporter tool? Does that work?

**Comment by muresanandrei** [comment]
No because I don't know java that's why I used this package :). But I will give it a try. Also would this packge be able to get promo codes?

**Comment by fedoco** [comment]
No, it can't fetch promo codes. Please read the official documentation: https://help.apple.com/itc/appsreporterguide/#/itcbe21ac7db

**Comment by muresanandrei** [comment]
Ok thank you for your answers you were very quick 👍

**Comment by mikebarlow** [comment]
Heh, thanks for replying quick Fedoco! I see you're the owner of the Python version!

@muresanandrei I'm at work right now so I'm unable to take a proper look but Fedoco is correct about the promo codes. 

With regards to the getSalesAccount returning an empty array, I will have to check when I get home from work this evening and see what it does for me. From there I should be able to work out what is happening.

**Comment by muresanandrei** [comment]
@mikebarlow Do you think you can add a method to extract the promo codes or is it possible with this package? Thanks.

**Comment by mikebarlow** [comment]
From the docs it looks like they have updated their reporter to 2.2 so that could be why the getSalesAccount has stopped working. This happened when they moved from 2.0 to 2.1.

As for Promo Codes, sadly not. As Fedoco posted above, this package is for the financial and sales reporting. It's a PHP version of the reporter.jar package Apple provide so unless they provide the ability to retrieve Promo codes via that then it won't be possible in this package.

**Comment by fedoco** [comment]
I'm experiencing occasional 502s and large delays with my Python version today – could be that it is nothing more than a temporary hiccup. Just FYI.

**Comment by muresanandrei** [comment]
Guys thank you so much for your answer really helped me to know how to proceed further. I am one of the creators and developer of https://usevalidator.com/. I have one final question is there a way to get the promo codes if I have the access token with php curl or even python ?

**Comment by mikebarlow** [comment]
If you're wanting just a list of all promo codes in your iTunes account then no. As stated, this API is purely for the financial and sales reports. That is it, all this package is, is a wrapper around the access token and php curl requests to the correct API endpoints that Apple provides. Apple does not provide an endpoint to retrieve the promo codes.

The only promo code you can get is the promo code used in each sale, and that's retrieved through the two types of reports that are provided by this package. But if you have a promo code that is not used by anyone, it won't appear in this report. Hope that makes sense.

**Comment by muresanandrei** [comment]
Thanks for the answer I actually need both financial and promo code. But I will see what I am going to do about promo codes. Will you update this package to be able to get the financial and sales reports?

**Comment by mikebarlow** [comment]
I'll have a look this evening and see if i can see what's wrong. The package already get's those reports but it looks like Apple have released an update which could have broken the package.

**Comment by mikebarlow** [comment]
@muresanandrei Are you still having problems?

Apologies for the delay, only just getting round to testing. I've been able to successfully get my sales accounts via the package.
